### ISSUE TITLE
Relicense under AGPL

### ISSUE THREAD

**Issue by eutampieri** [FrancescoBonzi/UniboCalendar#17]
GNU AGPLv3
Permissions of this strongest copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. **When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available**.

**Comment by FrancescoBonzi** [comment]
Done
