### ISSUE TITLE
Corsi ordinare per nome invece che per numero

### ISSUE THREAD

**Issue by rickycraft** [FrancescoBonzi/UniboCalendar#22]
Penso che possa essere più inutitivo ordinare per nome del corso invece che per id. Mi immagino che generalmente lo studente cerchi per nome di corso invece che per codice.

**Comment by FrancescoBonzi** [comment]
Ciao @rickycraft, grazie per il commento. Mi risulta che i corsi siano già presentati in ordine alfabetico, anche se viene inserito davanti al nome il codice del percorso di laurea.

**Comment by rickycraft** [comment]
Lo vedo in questo modo io.
![image](https://user-images.githubusercontent.com/36400508/188107883-dbcc0914-d29c-4f39-9103-78d9cb5c3f4e.png)

**Comment by FrancescoBonzi** [comment]
Ok, mi sono accorto che nella versione Desktop visualizza in ordine di codice, mentre su mobile ordina per nome del corso. Mi confermi che questo vale anche per te?

**Comment by rickycraft** [comment]
Dal telefono Android da cui ho testato mi risulta comunque ordinato per codice.

**Comment by FrancescoBonzi** [comment]
Forse allora dipende dal browser. Noto che Safari ordina in ordine alfabetico mentre Chrome per codice (sia su mobile che su desktop)

**Comment by rickycraft** [comment]
C'è un modo per evitare che questo succeda? Onestamente non ho visto il codice com'è scritto.

**Comment by FrancescoBonzi** [comment]
Si certo, nel codice viene già fatto un sort per descrizione, che però ha risultati diversi a seconda del browser, bisognerebbe capire perché... Nelle prossime settimane posso guardarci, ma se preferisci applicare la correzione subito puoi guardarci tu 😊
Il codice in questione è qui: https://github.com/FrancescoBonzi/UniboCalendar/blob/9927114feb9ee05a4d175ab15baad6ff876b4a38/public/scripts/home.js#L100
