### ISSUE TITLE
Outlook Calendar

### ISSUE THREAD

**Issue by FrancescoBonzi** [FrancescoBonzi/UniboCalendar#31]
Now, the link can only be added to Google Calendar or Apple Cal. Another widely used calendar in Unibo is Outlook Calendar. 
We need to look at how to add the shortcut on the last page, after the link generation (see the section field in        [this section block](https://github.com/FrancescoBonzi/UniboCalendar/blob/c02b80c302e506b2f049000e0f468cbf5a903ac9/views/link.handlebars#L25)). The link sent to the client as {{{url}}} is [here](https://github.com/FrancescoBonzi/UniboCalendar/blob/c02b80c302e506b2f049000e0f468cbf5a903ac9/model.js#L177).

**Comment by FrancescoBonzi** [comment]
Questa cosa ha senso? @eutampieri

**Comment by eutampieri** [comment]
I don’t think so
