### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by filippo-brigati** [FrancescoBonzi/UniboCalendar#36]
il sito non è più raggiungibile da questo indirizzo https://unibocalendar.it/

**Comment by FrancescoBonzi** [comment]
Grazie Filippo per la segnalazione, ora il sito è di nuovo online. Fammi sapere se ci sono altri problemi.

**Comment by filippo-brigati** [comment]
Ora funziona tutto, grazie mille.

Posso chiederti dove si trova il dataset che utilizzi? Ho provato a cercare sul sito di unibo ma ho trovato solo quello delle lezioni.

Grazie in anticipo

**Comment by FrancescoBonzi** [comment]
Unibo non mette a disposizione quel dataset che io sappia, quindi per ora faccio scraping dalle varie pagine degli orari dei corsi. Non è un granché, ma mettendoci una cache di un giorno in mezzo funziona, non è pesante e rimane aggiornato quotidianamente.

**Comment by FrancescoBonzi** [comment]
Purtroppo non ho niente da farti vedere perché abbiamo provato tutto a mano e siamo andati per tentativi. Se però guardi il codice qui https://github.com/FrancescoBonzi/UniboCalendar/blob/0c4b6673a2337ccf6dc9a7788b9203a55a8cb727/src/model.js#L233 puoi vedere che dagli opendata che dicevi tu sulle lezioni prendo le info che poi compongo insieme nel link dell'orario e poi lo parsifico sempre nello stesso modo.
Farlo con una tecnologia nuova è proprio un bell'esercizio. Se poi funziona e vuoi fare una pr top :)

**Comment by filippo-brigati** [comment]
okk allora ci guado subito grazie mille.

Alla fine ieri ho trovato un un dataset con all'interno le informazioni del corso tra cui la 'categoria', il problema è che non c'era il link diretto al sito del corso (che mi servirebbe per fare la chiamata per avere il JSON con gli orari).

Ho però creato uno script che naviga all'url nel dataset dove è presente un button che linka al sito del corso, una volta fatto lo scrape della pagina e preso il link che mi interessa vado ad aggiornare il .csv iniziale.

[questo](https://dati.unibo.it/dataset/degree-programmes/resource/4e0c15c7-1ead-4821-a6a0-62084a198ce5) è il link al dataset, se riesco a completare tutto poi metto anche lo screaper che va a sostituire il link.

In questo modo ho tutti i dati in un'unico file.

Grazie ancora per l'aiuto, se finisco tutto posso provare ad aprire la pr ma devo ancora guardarmi le api di Google Calendar

**Comment by FrancescoBonzi** [comment]
Esatto è lo stesso dataset che uso anche io. Qui invece è come uso la api di Google per aggiungere il calendario https://github.com/FrancescoBonzi/UniboCalendar/blob/0c4b6673a2337ccf6dc9a7788b9203a55a8cb727/src/views/link.handlebars#L28-L29

**Comment by FrancescoBonzi** [comment]
Per queste cose chatGPT può essere molto utile secondo me 😁
