### ISSUE TITLE
Events are created with an invalid URL

### ISSUE THREAD

**Issue by eutampieri** [FrancescoBonzi/UniboCalendar#39]
I.e. Non%20è%20disponibile%20una%20aula%20virtuale

To fix, check if the url is valid with this re: `/[A-Za-z\-]~\/\/.*/`

**Comment by FrancescoBonzi** [comment]
https://github.com/FrancescoBonzi/UniboCalendar/blob/eea5085ca222ab831d3cd68919789ecd08395ae2/src/model.js#L295
in questo blocco aggiungo le informazioni che vengono visualizzate male. Come si risolve però?
